######################################################################
# Automatically generated by qmake (3.0) Wed May 17 14:19:18 2017
######################################################################

TEMPLATE = app
TARGET = Sources
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS = -std=c++11 -lsqlite3
QMAKE_LFLAGS = -std=c++11 -lsqlite3

# Input
HEADERS += connexion.h Note.h timing.h
SOURCES += connexion.cpp main.cpp Note.cpp timing.cpp
